// Auto-generated
let project = new Project('prototype 1 armory');

project.addSources('Sources');
project.addLibrary("/home/redfill/Documents/Armory/armsdk/armory");
project.addLibrary("/home/redfill/Documents/Armory/armsdk/iron");
project.addLibrary("/home/redfill/Documents/Armory/armsdk/lib/haxebullet");
project.addAssets("/home/redfill/Documents/Armory/armsdk/lib/haxebullet/js/ammo/ammo.js", { notinlist: true });
project.addParameter('armory.trait.internal.Bridge');
project.addParameter("--macro keep('armory.trait.internal.Bridge')");
project.addParameter('armory.trait.physics.bullet.PhysicsWorld');
project.addParameter("--macro keep('armory.trait.physics.bullet.PhysicsWorld')");
project.addParameter('arm.RocketHaxe');
project.addParameter("--macro keep('arm.RocketHaxe')");
project.addParameter('armory.trait.physics.bullet.RigidBody');
project.addParameter("--macro keep('armory.trait.physics.bullet.RigidBody')");
project.addParameter('armory.trait.internal.DebugConsole');
project.addParameter("--macro keep('armory.trait.internal.DebugConsole')");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/armdefault_mesh.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/armdefault_mesh.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/hex_floor_mesh.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/hex_floor_mesh.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/hex_floor_shadowmap.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/hex_floor_shadowmap.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/metal_wall_mesh.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/bloom_pass.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/blur_edge_pass.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/blur_gaus_pass.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/compositor_pass.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/compositor_pass.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/deferred_indirect.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/deferred_indirect.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/deferred_light.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/deferred_light_quad.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/pass.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/pass_light_volume.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/pass_viewray.vert.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/ssao_pass.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/world_pass.frag.glsl");
project.addShaders("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/world_pass.vert.glsl");
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/armdefault_data.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/hex_floor_data.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/metal_wall_data.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Shaders/shader_datas.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Assets/Scene.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Assets/envmaps/World_irradiance.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Assets/meshes/mesh_Cone.001.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Assets/meshes/mesh_Cone.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Assets/meshes/mesh_Plane.004.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Assets/meshes/mesh_sector.001.arm", { notinlist: true });
project.addAssets("/home/redfill/Bureau/game dev/hot rocket/build_prototype 1 armory/compiled/Assets/meshes/mesh_sector.005.arm", { notinlist: true });
project.addAssets("/home/redfill/Documents/Armory/armsdk/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("/home/redfill/Documents/Armory/armsdk/armory/Assets/noise256.png", { notinlist: true });
project.addAssets("/home/redfill/Documents/Armory/armsdk/armory/Assets/noise8.png", { notinlist: true });
project.addAssets("textures/hexagon/HexagonTile_DIFF.png", { notinlist: true });
project.addAssets("textures/hexagon/HexagonTile_NRM.png", { notinlist: true });
project.addAssets("textures/hexagon/HexagonTile_SPEC.png", { notinlist: true });
project.addAssets("textures/metal wall/mjst_metal_base_diffuse.png", { notinlist: true });
project.addAssets("textures/metal wall/mjst_metal_base_normalbump.png", { notinlist: true });
project.addAssets("textures/metal wall/mjst_metal_base_specular.png", { notinlist: true });
project.addShaders("/home/redfill/Documents/Armory/armsdk//armory/Shaders/debug_draw/**");
project.addLibrary("/home/redfill/Documents/Armory/armsdk/lib/zui");
project.addAssets("/home/redfill/Documents/Armory/armsdk/armory/Assets/droid_sans.ttf", { notinlist: false });
project.addDefine('arm_deferred');
project.addDefine('arm_csm');
project.addDefine('rp_hdr');
project.addDefine('rp_renderer=Deferred');
project.addDefine('rp_depthprepass');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_size=1024');
project.addDefine('rp_background=World');
project.addDefine('rp_render_to_texture');
project.addDefine('rp_compositornodes');
project.addDefine('rp_antialiasing=FXAA');
project.addDefine('rp_supersampling=1');
project.addDefine('rp_gi=Off');
project.addDefine('rp_ssgi=SSAO');
project.addDefine('rp_bloom');
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
project.addDefine('arm_shaderload');
project.addDefine('arm_soundcompress');
project.addDefine('arm_debug');
project.addDefine('arm_ui');
project.addDefine('arm_skin');
project.addDefine('arm_particles_gpu');
project.addDefine('arm_particles');
project.addDefine('arm_fast');


resolve(project);
